services:
  flask:
    build: .
    container_name: vuln_flask
    volumes:
      - ./app:/app
    expose:
      - "5000"

  nginx:
    image: nginx:1.19.10
    container_name: vuln_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/app
    depends_on:
      - flask

  redis:
      image: redis
      container_name: redis-container
      ports:
        - "6379:6379"
      command: ["redis-server", "--requirepass", "hCQr7gvbyRRN79Ugvc9Lssq6"]